### ISSUE TITLE
Button to report issues / new features are not working

### ISSUE THREAD

**Issue by djavorszky** [alffox/around-the-world#1]
At least in Firefox :-)

**Comment by alffox** [comment]
Thanks for reporting Dani @djavorszky  !

This has been now fixed through 77fe67de96204d7c72643afc8782d4892b95c88b and 48d34b4cdb699ef43a8d7bec18846e93946284ca

Feel free to reopen this in case of anything.

**Comment by djavorszky** [comment]
Thanks @alffox! :)
